const mongoose = require('mongoose');
const Product = require('./models/Product'); // Import Product model

mongoose.connect('your_mongodb_url', {
  useNewUrlParser: true,
  useUnifiedTopology: true,
});

const products = [
  {
    id: 1,
    title: 'Fjallraven - Foldsack No. 1 Backpack',
    price: 109.95,
    description: 'Perfect pack for everyday use and walks in the forest.',
    category: 'men\'s clothing',
    image: 'https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg',
    rating: { rate: 3.9, count: 120 },
  },
  {
    id: 2,
    title: 'Mens Casual Premium Slim Fit T-Shirts',
    price: 22.3,
    description: 'Slim-fitting style with stretch for comfort.',
    category: 'men\'s clothing',
    image: 'https://fakestoreapi.com/img/71YXzeOuslL._AC_UY879_.jpg',
    rating: { rate: 4.1, count: 259 },
  },
  {
    id: 3,
    title: 'Solid Gold Petite Micropave',
    price: 168,
    description: 'Satisfaction guaranteed.',
    category: 'jewelery',
    image: 'https://imgs.search.brave.com/tFj8Hdi3rDts9P-XCyWwGgJ9WJdF-zTdkE91jcDXCfE/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pbWFn/ZXMtbmEuc3NsLWlt/YWdlcy1hbWF6b24u/Y29tL2ltYWdlcy9J/LzYxZWR3em5HTk1M/LmpwZw',
    rating: { rate: 4.6, count: 400 },
  },
  {
    id: 4,
    title: 'White Gold Plated Princess',
    price: 9.99,
    description: 'Classic created diamond princess ring.',
    category: 'jewelery',
    image: 'https://fakestoreapi.com/img/71YAIFU48IL._AC_UL640_QL65_ML3_.jpg',
    rating: { rate: 3.0, count: 70 },
  },
  {
    id: 5,
    title: 'WD 2TB Elements Portable External Hard Drive',
    price: 64,
    description: 'Fast data transfers and plug-and-play functionality.',
    category: 'electronics',
    image: 'https://fakestoreapi.com/img/61IBBVJvSDL._AC_SY879_.jpg',
    rating: { rate: 4.5, count: 203 },
  },
  {
    id: 6,
    title: 'SanDisk SSD PLUS 1TB Internal SSD',
    price: 109,
    description: 'Easy upgrade for faster boot and better performance.',
    category: 'electronics',
    image: 'https://fakestoreapi.com/img/61U7T1koQqL._AC_SX679_.jpg',
    rating: { rate: 4.6, count: 470 },
  },
  {
    id: 7,
    title: 'BIYLACLESEN Women\'s Rain Jacket',
    price: 39.99,
    description: 'Lightweight perfect for climbing, cycling, and other outdoor activities.',
    category: 'women\'s clothing',
    image: 'https://fakestoreapi.com/img/71HblAHs5xL._AC_UY879_-2.jpg',
    rating: { rate: 4.2, count: 300 },
  },
  {
    id: 8,
    title: 'Lock and Love Women\'s Removable Hooded Jacket',
    price: 29.95,
    description: 'Casual lightweight jacket for everyday wear.',
    category: 'women\'s clothing',
    image: 'https://imgs.search.brave.com/jWLrU9pYHIVuYxXP7KpNA4E83mE6_nh0oK-iTj3C2Gg/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pbWFn/ZXMtbmEuc3NsLWlt/YWdlcy1hbWF6b24u/Y29tL2ltYWdlcy9J/LzcxbWFRNE1HZllM/LmpwZw',
    rating: { rate: 3.8, count: 250 },
  },
  {
    id: 9,
    title: 'John Hardy Women\'s Classic Chain Bracelet',
    price: 695,
    description: 'From the John Hardy Classic Chain Collection.',
    category: 'jewelery',
    image: 'https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg',
    rating: { rate: 4.6, count: 340 },
  },
  {
    id: 10,
    title: 'MBJ Women\'s Solid Short Sleeve Boat Neck',
    price: 9.85,
    description: 'Casual T-shirt with comfort.',
    category: 'women\'s clothing',
    image: 'https://fakestoreapi.com/img/71z3kpMAYsL._AC_UY879_.jpg',
    rating: { rate: 4.1, count: 289 },
  },
  {
    id: 11,
    title: 'DANVOUY Women\'s T-Shirt Casual Cotton Short',
    price: 12.99,
    description: 'Lightweight, classic fit.',
    category: 'women\'s clothing',
    image: 'https://imgs.search.brave.com/kTKcvRlG5Z30_g4t4fUk5IrPioAeyZWvlKgQThvHFSU/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pbWFn/ZXMtbmEuc3NsLWlt/YWdlcy1hbWF6b24u/Y29tL2ltYWdlcy9J/LzUxUFdGMzExb1NM/LmpwZw',
    rating: { rate: 4.2, count: 200 },
  },
  {
    id: 12,
    title: 'Apple MacBook Pro 13-inch',
    price: 1200,
    description: 'M2 chip for faster performance and longer battery life.',
    category: 'electronics',
    image: 'https://imgs.search.brave.com/Y1DN2qRFois7fWkvbMuGv4W9_gCwmXASePlKfue0jjc/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pbWFn/ZXMtbmEuc3NsLWlt/YWdlcy1hbWF6b24u/Y29tL2ltYWdlcy9J/LzcxaTQ5TTRodjJM/LmpwZw',
    rating: { rate: 4.8, count: 500 },
  },
  {
    id: 13,
    title: 'Noise Cancelling Headphones',
    price: 199.99,
    description: 'Experience immersive sound quality.',
    category: 'electronics',
    image: 'https://imgs.search.brave.com/L_5q4TKzvg8JefSYO5a0HXWmwJ_-c4zfoBGNA-vTLHY/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9rb3Nz/LmNvbS9jZG4vc2hv/cC9maWxlcy9Lb3Nz/LUJUNzQwaS1RWl9O/b2lzZS1DYW5jZWxs/aW5nLVdpcmVsZXNz/LUhlYWRwaG9uZXNf/ZTg2MmQ2ODItOTVl/Ni00MjVlLWEwNmEt/MDBmYzBlNjRjMWFj/LmpwZz9jcm9wPWNl/bnRlciZoZWlnaHQ9/MjA0OCZ2PTE2ODU2/MzE5MjEmd2lkdGg9/MjA0OA',
    rating: { rate: 4.7, count: 420 },
  },
  {
    id: 14,
    title: 'Nike Air Max Running Shoes',
    price: 120,
    description: 'Comfortable running shoes for all terrains.',
    category: 'men\'s clothing',
    image: 'https://imgs.search.brave.com/ZertejwRCvyO_aNxImylIjiX_xCFHw_tKU_BhY3OM9o/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tLm1l/ZGlhLWFtYXpvbi5j/b20vaW1hZ2VzL0kv/NjFnRytORU9obUwu/anBn',
    rating: { rate: 4.3, count: 350 },
  },
  {
    id: 15,
    title: 'Adidas Women\'s Joggers',
    price: 45,
    description: 'Stylish and comfortable.',
    category: 'women\'s clothing',
    image: 'https://imgs.search.brave.com/8oNFkrfuW72tjEa5ei1VXPJHbOmCOqR2c_jtGS3E48k/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tLm1l/ZGlhLWFtYXpvbi5j/b20vaW1hZ2VzL0kv/NjFZaWZBLThPNUwu/anBn',
    rating: { rate: 4.5, count: 310 },
  },
  {
    id: 16,
    title: 'Casio Digital Watch',
    price: 25,
    description: 'Classic Casio watch.',
    category: 'jewelery',
    image: 'https://imgs.search.brave.com/bOyG_mS9TLdTAIEN8MIHFv7Amvr_Ua8OSdwrvQelyGg/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tLm1l/ZGlhLWFtYXpvbi5j/b20vaW1hZ2VzL0kv/NzFnMGs3NjdxWkwu/anBn',
    rating: { rate: 4.0, count: 250 },
  },
  {
    id: 17,
    title: 'KitchenAid Mixer',
    price: 250,
    description: 'Perfect for baking enthusiasts.',
    category: 'electronics',
    image: 'https://imgs.search.brave.com/S0r117teST1MSqvtnsFs72GhsONuryHYRAzs3HHPdgA/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5nZXR0eWltYWdl/cy5jb20vaWQvNTM2/MDUzODc5L3Bob3Rv/L2tpdGNoZW4tYWlk/LXByb2Zlc3Npb25h/bC02MDAtbWl4ZXIu/anBnP3M9NjEyeDYx/MiZ3PTAmaz0yMCZj/PXR3YlVNa0hwUTh3/Rm9ySG55a0hZdTZV/V3V4YlZyQWhSeW4x/cV94blhUOE09',
    rating: { rate: 4.9, count: 510 },
  },
  {
    id: 18,
    title: 'Ray-Ban Sunglasses',
    price: 99.99,
    description: 'Stylish sunglasses with UV protection.',
    category: 'jewelery',
    image: 'https://imgs.search.brave.com/wAeSTqgKmF0SzqPNkKlzuKnfNJY_sDrOIdtWbRsSL1Q/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly93d3cu/ZnJhbWVzZGlyZWN0/LmNvbS9wcm9kdWN0/X2VsYXJnZV9pbWFn/ZXMvUmF5LUJhbi1D/bHVibWFzdGVyLU1l/dGFsLTE4Ni1SNS1C/bGFjay1CbHVlLWEu/anBn',
    rating: { rate: 4.4, count: 280 },
  },
  {
    id: 19,
    title: 'Samsung Galaxy S21',
    price: 799,
    description: 'Flagship smartphone with excellent features.',
    category: 'electronics',
    image: 'https://imgs.search.brave.com/XwYcJK-WEQBMh55Fq2najaClZseXnAN_VplSHHVQhkE/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tLm1l/ZGlhLWFtYXpvbi5j/b20vaW1hZ2VzL0kv/MzFBUE5YSWhjakwu/anBn',
    rating: { rate: 4.7, count: 490 },
  },
  {
    id: 20,
    title: 'The Alchemist',
    price: 15.99,
    description: 'Inspirational story by Paulo Coelho.',
    category: 'books',
    image: 'https://imgs.search.brave.com/TRGDdeYqA2r_I3XzsmUdQcBHztYS0C1RQ1CFH-NLf4k/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9oNy5h/bGFteS5jb20vY29t/cC9DOTEyOEUvdGhl/LWFsY2hlbWlzdC1i/eS1wYXVsby1jb2Vs/aG8tQzkxMjhFLmpw/Zw',
    rating: { rate: 4.8, count: 620 },
  },
];

Product.insertMany(products)
  .then(() => {
    console.log('Sample products added');
    mongoose.connection.close();
  })
  .catch((err) => console.error(err));