// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6DV_B4EZZUmCzgywI2kukCeyYhiTas0M',
    appId: '1:19720314738:web:dde78189d07314708607eb',
    messagingSenderId: '19720314738',
    projectId: 'ecommerceappexample-51b47',
    authDomain: 'ecommerceappexample-51b47.firebaseapp.com',
    storageBucket: 'ecommerceappexample-51b47.firebasestorage.app',
    measurementId: 'G-XM6HQHJ9GQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnDpdY9BhZGkg-pWVuE7h8SKZgDZTjFB4',
    appId: '1:19720314738:android:55db0f5ce5aa2b578607eb',
    messagingSenderId: '19720314738',
    projectId: 'ecommerceappexample-51b47',
    storageBucket: 'ecommerceappexample-51b47.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA08E-WcX25aZyNj5RW9eaG9jhx4YcHaY8',
    appId: '1:19720314738:ios:71c4fa88afd574ef8607eb',
    messagingSenderId: '19720314738',
    projectId: 'ecommerceappexample-51b47',
    storageBucket: 'ecommerceappexample-51b47.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceAppExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA08E-WcX25aZyNj5RW9eaG9jhx4YcHaY8',
    appId: '1:19720314738:ios:71c4fa88afd574ef8607eb',
    messagingSenderId: '19720314738',
    projectId: 'ecommerceappexample-51b47',
    storageBucket: 'ecommerceappexample-51b47.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceAppExample',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6DV_B4EZZUmCzgywI2kukCeyYhiTas0M',
    appId: '1:19720314738:web:ecdb3bbd907085668607eb',
    messagingSenderId: '19720314738',
    projectId: 'ecommerceappexample-51b47',
    authDomain: 'ecommerceappexample-51b47.firebaseapp.com',
    storageBucket: 'ecommerceappexample-51b47.firebasestorage.app',
    measurementId: 'G-NL2RL9CP6T',
  );
}
